
#
# Demo and dev stack configuration
#

backend:
  build: ./backend
  links:
    - postgresdb
    - mailhog
  ports:
    - "3500:3500"
  environment:
    - POSTGRES_HOST=postgresdb
    - CLIENT_ID=656587629888-4rvd0pv398dgderln9s6kuvr7kdn99k5.apps.googleusercontent.com
    - FROM_EMAIL=codechallenge@twostoryrobot.com
    - SMTP=smtp://mailhog:1025

frontend:
  build: ./frontend
  ports:
    - "3000:80"

postgresdb:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=postgresadmin

postgres-seed:
  build: ./postgres-seed
  links:
    - postgresdb
  environment:
    - PGPASSWORD=postgresadmin

postgresdb-test:
  image: postgres
  ports:
    - "5544:5432"
  environment:
    - POSTGRES_PASSWORD=postgrestest

postgres-seed-test:
  build: ./postgres-seed-test
  links:
    - postgresdb-test
  environment:
    - PGPASSWORD=postgrestest

mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"
