postgresdb:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=postgresadmin

postgres-seed:
  build: ./postgres-seed
  links:
    - postgresdb
  environment:
    - PGPASSWORD=postgresadmin

postgresdb-test:
  image: postgres
  ports:
    - "5544:5432"
  environment:
    - POSTGRES_PASSWORD=postgrestest

postgres-seed-test:
  build: ./postgres-seed-test
  links:
    - postgresdb-test
  environment:
    - PGPASSWORD=postgrestest

mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"
