postgresdb:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=postgresadmin

postgres-seed:
  build: ./postgres-seed
  links:
    - postgresdb
  environment:
    - PGPASSWORD=postgresadmin

mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"
